package uk.ac.ed.inf.aqmaps;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

import com.mapbox.geojson.Feature;
import com.mapbox.geojson.FeatureCollection;
import com.mapbox.geojson.LineString;

public final class FileOutput {

	private FileOutput() {
		// This is a small helper class that is never instantiated, hence private
		// constructor
	}

	public static void logFlightPath(ArrayList<String> flightPath, String filename) {
		// Take the flightpath generated by the done and publish it to file
		try {
			var writer = new FileWriter(filename);
			// Final check that the log does not exceed 150
			for (int move = 0; move < 150; move++) {
				writer.write(flightPath.get(move) + System.lineSeparator());
			}
			writer.close();
			System.out.println("Successfully logged flight path to the file " + filename);
		} catch (IOException e) {
			System.out.println("Could not log flight path");
			e.printStackTrace();
		}
	}

	public static void createGeoJSON(LineString l, ArrayList<Feature> sensors, String filename) {
		sensors.add(Feature.fromGeometry(l));
		var featureCollection = FeatureCollection.fromFeatures(sensors);
		try {
			var writer = new FileWriter(filename);
			System.out.println(featureCollection.toJson());
			writer.write(featureCollection.toJson());
			writer.close();
			System.out.println("Successfully created the geojson in " + filename);
		} catch (IOException e) {
			System.out.println("Error in GeoJSON file creation");
			e.printStackTrace();
		}
	}

}
